version: '2.1'
orbs:
  terraform: circleci/terraform@3.1
workflows:
  deploy_infrastructure:
    jobs:
      - terraform/fmt:
          checkout: true
      - terraform/validate:
          checkout: true
          requires:
            - terraform/fmt
      - terraform/plan:
          checkout: true
          persist-workspace: true
          requires:
            - terraform/validate
      # - terraform/apply:
      #     attach-workspace: true
      #     context: terraform
      #     filters:
      #       branches:
      #         only: main
      #     requires:
      #       - terraform/plan

# VS Code Extension Version: 1.0.0