version: '2.1'  
workflows:
  deploy_infrastructure:
    jobs:
      - terraform-test

jobs:
  terraform-test:
    docker: 
      - image: cimg/aws:2022.06.1
    steps:
      - checkout
      - run: terraform test
# VS Code Extension Version: 1.0.0