version: '2.1'
orbs:
  terraform: circleci/terraform@3.1
workflows:
  deploy_infrastructure:
    jobs:
        - terraform-validate
      # - terraform/validate:
      #     checkout: true
      #     path: "./testing/"
      # - terraform/plan:
      #     checkout: true
      #     path: "./testing/"
      #     persist-workspace: true
      #     requires:
      #       - terraform/validate
      # - terraform/apply:
      #     attach-workspace: true
      #     context: terraform
      #     filters:
      #       branches:
      #         only: main
      #     requires:
      #       - terraform/plan



jobs:
  terraform-validate:
    docker:
      - image: cimg/aws:2022.06.1
    steps: 
      - checkout
      - enable-oidc
      - terraform/validate:
          path: "./testing/"

commands:
  enable-oidc:
    steps:
      - run:
          name: authenticate-and-interact
          command: |
            # use the OpenID Connect token to obtain AWS credentials
            read -r AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN \<<< \
              $(aws sts assume-role-with-web-identity \
              --role-arn ${AWS_ROLE_ARN} \
              --role-session-name "CircleCI-${CIRCLE_WORKFLOW_ID}-${CIRCLE_JOB}" \
              --web-identity-token $CIRCLE_OIDC_TOKEN \
              --duration-seconds 3600 \
              --query 'Credentials.[AccessKeyId,SecretAccessKey,SessionToken]' \
              --output text)
            export AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN
            # interact with AWS
            aws sts get-caller-identity
            echo "export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}" >> $BASH_ENV
            echo "export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}" >> $BASH_ENV
            echo "export AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}" >> $BASH_ENV
            source $BASH_ENV

# VS Code Extension Version: 1.0.0